Accordion with upload button
PramodaM4444/internal_app pull request #13
Opened 2022-05-12 11:38 UTC by akshitha-r

2022-05-13 07:44 UTC, PramodaM4444 requested changes
Why I am seeing the changes in Example.tsx and other files in this PR where there is no changes made? It will be hard to identify the new changes. Also pls make sure the PR branch is updated when compared to the dev branch by resolving the merge conflicts.

2022-05-18 12:15 UTC, akshitha-r commented
I have merged and now there are no conflicts with the base branch.

2022-05-18 13:51 UTC, PramodaM4444 commented on src/containers/Timesheet/Timesheet.tsx
> +                <Typography>ILC Details</Typography>
Pls import the text from Constants file

2022-05-18 13:53 UTC, PramodaM4444 commented on src/containers/Timesheet/Timesheet.tsx
> +                    style={{ width: 800 }}
Make use of 'rem' for CSS units

2022-05-18 15:34 UTC, aritraibm submitted a review, later dismissed

2022-05-18 15:34 UTC, aritraibm commented on src/App.tsx
> +                <Route path="/timesheet" element={<Timesheet />} />
I might be wrong, but are we removing existing code, could you please double-check once? thanks

2022-05-18 15:34 UTC, aritraibm commented on src/containers/Timesheet/Timesheet.tsx
> +        <h4>Upload ILC</h4>
As per our agreed coding guidelines, we are supposed to use the UI constant file for all of the static labels/ texts, pls change it, thanks

2022-05-18 15:34 UTC, aritraibm commented on src/containers/Timesheet/Timesheet.tsx
> +                <Box m={1} display="flex" justifyContent="flex-end">
in-line style properties are good but sometimes it's very hard to maintain when the application is getting large. we can use the class/ styled component, thanks

2022-05-18 15:34 UTC, aritraibm commented on src/containers/Timesheet/Timesheet.tsx
> +                <TextareaAutosize
To handle errors and other scenarios, can we create a component (like dropdown/ textbox), you can use **Textarea** which is already there. Also, from a look and feel point of view **TextareaAutosize** is not align with Material UI design (However it's a part of MUI)

2022-05-18 16:48 UTC, aritraibm commented on src/containers/Timesheet/Timesheet.tsx
> +                <Box m={1} display="flex" justifyContent="flex-end">
I'm okay if it's a part of MUI Box API or prop

2022-05-26 08:04 UTC, PramodaM4444 approved these changes

2022-05-30 12:02 UTC, ShubhamAgrawa approved these changes

2022-06-01 10:54 UTC, merged